---
# file: playbooks/roles/gateways/tasks/tsk_tunneldigger.yaml
#
# Thomas Arend
# Date 2019-04-13
#
#

#
# Install yanic
#

- name: Create Yanic user
  user:
    name: yanic
    comment: "Yanic service user"
  tags:
    - yanic

- name: Create Yanic folder
  file: 
    path: /opt/freifunk/yanic
    state: directory
    mode: 0755
    owner: yanic
    group: yanic
  tags:
    - yanic

- name: Copy yanic config template
  template:
    src: yanic.conf.j2
    dest: /etc/yanic.conf
    owner: yanic
    group: yanic
    mode: 0444
  tags:
    - yanic

- name: Activate yanic webserver
  ini_file:
    path: /etc/yanic.conf
    section: webserver
    option: enable
    value: "true"
  when: supernode.yanic.web_port is defined
  tags:
    - yanic
    
- name: Set correct yanic webserver bindings and port
  ini_file:
    path: /etc/yanic.conf
    section: webserver
    option: bind
    value: "{{ ansible_default_ipv4.address }}:{{ supernode.yanic.web_port }}"
  when: supernode.yanic.web_port is defined
  tags:
    - yanic 

- name: open up the yanik webport
  lineinfile: dest=/etc/ferm/ferm.conf
              line='proto tcp dport ( {{ supernode.yanic.web_port }} ) ACCEPT;'
              insertafter='# Ansible specified INPUT rules.'
  when: supernode.yanic.web_port is defined and supernode.yanic.expose == true 
  tags: 
    - yanic    
              
- name: Restart firewall ferm (ferm.service)
  service:
    name: "ferm.service"
    state: restarted
  when: supernode.yanic.web_port is defined and supernode.yanic.expose == true 
  tags: 
    - yanic     
    
- name: Compile yanic with go
  shell: "go get -v -u github.com/{{ github_user }}/yanic"
  ignore_errors: True
  register: compile_yanic
  tags:
    - yanic
  
- name: Copy and enable yanic service
  shell: "cp /opt/go/src/github.com/{{ github_user }}/yanic/contrib/init/linux-systemd/yanic.service /lib/systemd/system/yanic.service && systemctl daemon-reload && systemctl enable yanic"
  when: compile_yanic is succeeded
  tags:
    - yanic

- name: Restart yanic
  service:
    name: yanic.service
    state: restarted
  tags:
    - yanic                  
...
