---
# Erstellt von: Thomas Arend
# Erstellt am:  2019-06-23

- name: Delete servers and pool from ntp.conf
  lineinfile:
    dest: /etc/ntp.conf
    regexp: '(^pool|^server) .*'
    state: absent
  when: ntp_provider is defined
  tags:
    - ntp  

- name: Insert server into /etc/ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    line: "server {{ item }} iburst"
  loop: "{{ provider | list }}"
  when: provider is defined
  tags:
    - ntp  
  
- name: Restart ntp
  service:
    name: ntp.service
    state: restarted
  when: provider is defined
  tags:
    - ntp  
...
